ekzamen/ekzamen/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.conf.urls.static import static

urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ekzamen/main/urls.py
from itertools import product

from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
   path('', index, name='index'),
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('accounts/profile/', profile, name='profile'),
   path('about/', about, name='about'),
   path('contacts/', contacts, name='contacts'),
   path('product/', product, name='product'),
]

ekzamen/main/models.py
from datetime import datetime
from os.path import splitext

from django.db import models

from django.utils.crypto import get_random_string

from .utilities import get_timestamp_path


def get_name_file(instanse, filename):
    return '/'.join([get_random_string(length=5) + '_' + filename])


class Product(models.Model):
    name = models.CharField(max_length=254, verbose_name='Имя', blank=False)
    descriptions = models.TextField(verbose_name='описание', blank=True)
    photo_file = models.ImageField(max_length=254, upload_to=get_timestamp_path,
                                   blank=True, null=True)

ekzamen/main/forms.py
from django import forms

from .models import Product


class OrderCreate(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'descriptions', 'photo_file')
        enctype = "multipart/form-data"

ekzamen/main/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .forms import OrderCreate
from .models import Product


def index(request):
    res = Product.objects.all()
    return render(request, 'main/index.html', {'res': res})


class LoginView(LoginView):
    template_name = 'main/login.html'
    success_url = reverse_lazy('main/index.html')


class LogoutView(LogoutView):
    template_name = 'main/logout.html'


@login_required
def profile(request):
    if request.method == 'POST':
        form = OrderCreate(request.POST, request.FILES)
        form.save()
        return redirect('/product')
    else:
        form = OrderCreate
    context = {'form': form}
    return render(request, 'main/profile.html', context)


def about(request):
    return render(request, 'main/about.html')


def contacts(request):
    return render(request, 'main/contacts.html')


def product(request):
    return render(request, 'main/product.html')

ekzamen/main/templates/layout/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<header>
<a href="{% url 'main:index' %}">главная страница</a>
<a href="{% url 'main:product' %}">продукт</a>
<a href="{% url 'main:about' %}">О нас</a>
<a href="{% url 'main:contacts' %}">контакты</a>
{% if user.is_authenticated %}
<a href="{% url 'main:profile' %}">профиль</a>
<a href="{% url 'main:logout' %}">выход</a>
{% else %}
<a href="{% url 'main:login' %}">вход</a>
{% endif %}
</header>
<main>
{%block content%}
{%endblock%}

{%block about%}
{%endblock%}

{%block contacts%}
{%endblock%}

{%block product%}

{%endblock%}
</main>
</body>
</html>

ekzamen/main/templates/main/about.html
{% extends "layout/base.html" %}


{%block about%}
<p>о нас</p>
{%endblock%}

ekzamen/main/templates/main/contacts.html
{% extends "layout/base.html" %}


{%block contacts%}
<p>контакты</p>
{%endblock%}

ekzamen/main/templates/main/index.html
{% extends "layout/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% block content %}
<p>здесь будут вывыодится краткие описания услуг</p>
{% for item in res %}
{{item.name}}<br>
{{item.descriptions}}<br>
 <img style="width: 100px" src="media/{{ item.photo_file }}"><br>
{% endfor %}
{% endblock %}
</body>
</html>

ekzamen/main/templates/main/login.html
{% extends "layout/base.html" %}
{% block content %}

<div class="main">
    <div class="all_reg">
    <h1 class="auth">Аутентификация</h1>
    {% if form.errors %}
        <div class="alert-danger">
            <p class="p-1">Не правильный логин или пароль</p>
        </div>
    {% endif %}
    {% if is_authenticated %}
        <p>Вы уже авторизированы. <a href="{% url 'main:logout' %}">Выйти</a></p>
    {% else %}
        <form  method="post" action="{% url 'main:login' %}">
            {% csrf_token %}
            <table>
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
            </table>
            <input class="btno" type="submit" value="Войти">
            <input type="hidden" name="next" value="{{ next }}">
        </form>
    </div>
</div>
    {% endif %}

{% endblock %}

ekzamen/main/templates/main/logout.html
{% extends "layout/base.html" %}

{% block title %} Выход {% endblock %}

{% block content %}
   <h2>Выход</h2>
   <p>Вы успешно вышли с сайта.</p>
{% endblock %}

ekzamen/main/templates/main/product.html
{% extends "layout/base.html" %}


{%block product%}
<p>Здесь будут показываться ваши товары</p>
{%endblock%}

ekzamen/main/templates/main/profile.html
{% extends "layout/base.html" %}
{% load bootstrap4 %}

{%block content%}
<p>добавление ваших услуг</p>
<div class="center">
   <h1 class="text_center_create">Создание заявки</h1>
   <form method="post" enctype="multipart/form-data">
       {% csrf_token %}
       {{order.user}}
       {% bootstrap_form form layout='horizontal' %}
       {% buttons submit='Добавить' %} {% endbuttons %}
   </form>
</div>
{%endblock%}